### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by brandon-reinhart** [Razaekel/noise-rs#290]
I notice that there are a bunch of features that aren't in 0.7.0, like the iter() access to noise map!

**Comment by Keelar** [comment]
This would be nice. I just wasted way too much time wondering why I can't get stuff from the examples to compile. Turns out the release on crates.io is a year and a half old and most of the examples don't even work on the current release...

**Comment by jeffreyrosenbluth** [comment]
I would like to see a new release as well. There are features in it that I use regularly. Is there anything I can do to help?

**Comment by FelixSelter** [comment]
For now we have to git clone this into our application root and add the following to cargo.toml
```toml
[dependencies]
noise = {path = "./noise-rs"}
```

**Comment by yokunjon** [comment]
> For now we have to git clone this into our application root and add the following to cargo.toml
> 
> ```toml
> [dependencies]
> noise = {path = "./noise-rs"}
> ```
This is also possible:

```toml
[dependencies]
noise = { git = "https://github.com/Razaekel/noise-rs" }
```
